# Colors
COLOR_PLACEHOLDER = (150, 150, 150)

# Camera interface
MINI_STICKER_AREA_TILE_SIZE = 14
MINI_STICKER_AREA_TILE_GAP = 2
MINI_STICKER_AREA_OFFSET = 20

STICKER_AREA_TILE_SIZE = 30
STICKER_AREA_TILE_GAP = 4
STICKER_AREA_OFFSET = 20

STICKER_CONTOUR_COLOR = (36, 255, 12)
CALIBRATE_MODE_KEY = 'c'
TEXT_SIZE = 100

# Config
CUBE_PALETTE = 'cube_palette'

# Application errors
ERROR_MISSING_SIDES = 'Some sides are still not scanned'
ERROR_INCORRECTLY_SCANNED = 'Incorrectly scanned'
ERROR_ALREADY_SOLVED = 'Already solved'
